Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  nodes = [
    { name: "k8s-master",  ip: "192.168.100.10" },
    { name: "k8s-worker1", ip: "192.168.100.11" },
    { name: "k8s-worker2", ip: "192.168.100.12" },
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |vm|
      vm.vm.hostname = node[:name]
      vm.vm.network "public_network", bridge: "k8s-switch"

      vm.vm.provider "hyperv" do |hv|
        hv.vmname = node[:name]
        hv.memory = 4096
        hv.cpus = 2
      end

      # Configure static IP using nmcli (AlmaLinux/RHEL style)
      vm.vm.provision "shell", inline: <<-SHELL
        # Get the active connection name (not interface name)
        CON_NAME=$(nmcli -t -f NAME,DEVICE con show --active | head -1 | cut -d: -f1)
        echo "Using connection: $CON_NAME"
        
        nmcli con mod "$CON_NAME" \
          ipv4.addresses #{node[:ip]}/24 \
          ipv4.gateway 192.168.100.1 \
          ipv4.dns 8.8.8.8 \
          ipv4.method manual
        nmcli con up "$CON_NAME"

        # Add all nodes to /etc/hosts
        echo "192.168.100.10 k8s-master" >> /etc/hosts
        echo "192.168.100.11 k8s-worker1" >> /etc/hosts
        echo "192.168.100.12 k8s-worker2" >> /etc/hosts

        echo 'vagrant ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/vagrant
      SHELL
    end
  end
end